### ISSUE TITLE
hibari.moe: "Error: TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by archaephyrryx** [wopian/hibari#352] opened 2017-10-15 23:24 UTC
I understand that the site "hibari.moe" is a very early alpha, but I felt that I should let you know of this error in case you were unaware of it (which I doubt, however).

Almost any search I have tried to make results in a fraction of a second of a stat display with the Noh-face user icon, which immediately redirects to an error page with the listed error displayed.

**Comment by wopian** [comment] 2017-10-16 03:29
Duplicate of https://github.com/wopian/hibari/issues/315#issuecomment-335208932

**Closed by wopian** 2017-10-16 03:29 UTC
